CREATE USER '$kbaUser'@'$sqlDomainName' IDENTIFIED BY '$kbaPassword';

GRANT USAGE ON * . * TO '$kbaUser'@'$sqlDomainName' IDENTIFIED BY '$kbaPassword' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

CREATE DATABASE IF NOT EXISTS `$kbaDatabase` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `$kbaDatabase` . * TO '$kbaUser'@'$sqlDomainName';

FLUSH PRIVILEGES;

